# Build worker.env for the PC worker from the Railway project's variables.
#
# The PC worker runs the same pipeline as prod, so it needs the same shared
# state: Railway Postgres (PUBLIC url - the worker is outside Railway's
# private network), the R2 bucket, and the tokens/secrets the pipeline's
# publish + render-signing steps use. This script copies them WITHOUT ever
# printing a value.
#
# Usage (from the repo root, with the Railway CLI linked):
#   powershell -ExecutionPolicy Bypass -File scripts\make_worker_env.ps1
#
# Output: .\worker.env (gitignored). Start the worker with:
#   .\scripts\run_pc_worker.ps1

$ErrorActionPreference = "Stop"

$app = railway variables --service ChalybClip --json | ConvertFrom-Json
$pg  = railway variables --service Postgres --json | ConvertFrom-Json

# Everything the pipeline needs on the worker side, copied verbatim.
$copyKeys = @(
    "CHALYBCLIP_OBJECT_STORAGE_ACCESS_KEY_ID",
    "CHALYBCLIP_OBJECT_STORAGE_SECRET_ACCESS_KEY",
    "CHALYBCLIP_OBJECT_STORAGE_BUCKET",
    "CHALYBCLIP_OBJECT_STORAGE_ENDPOINT",
    "CHALYBCLIP_OBJECT_STORAGE_REGION",
    "CHALYBCLIP_MODAL_TOKEN",
    "CHALYBCLIP_INTERNAL_SIGNING_SECRET",
    "CHALYBCLIP_ZERNIO_API_KEY",
    "CHALYBCLIP_PUBLIC_URL",
    "CHALYBCLIP_CHALYB_BASE_URL",
    "CHALYBCLIP_CHALYB_ADMIN_TOKEN"
)

$lines = @(
    "# Generated by scripts/make_worker_env.ps1 - DO NOT COMMIT.",
    "# Shared Postgres (public URL - the worker lives outside Railway).",
    "DATABASE_URL=$($pg.DATABASE_PUBLIC_URL)"
)
foreach ($k in $copyKeys) {
    $v = $app.$k
    if ($null -ne $v -and "$v" -ne "") { $lines += "$k=$v" }
}
$lines += @(
    "# PC-local settings.",
    "CHALYBCLIP_TRANSCRIBE_PROVIDER=local",
    "CHALYBCLIP_WHISPER_DEVICE=cuda",
    # small+int8 fits alongside the resident Ollama LLM on an 8GB card;
    # medium+float16 (the code default) OOM-crashed the whisper worker.
    "CHALYBCLIP_WHISPER_MODEL=small",
    "CHALYBCLIP_WHISPER_COMPUTE_TYPE=int8_float16",
    "CHALYBCLIP_DEFAULT_OUTPUT_DIR=$env:LOCALAPPDATA\chalybclip-worker\out",
    "CHALYBCLIP_JOB_DISPATCHER=in_process"
)

Set-Content -Path "worker.env" -Value ($lines -join "`n") -Encoding utf8 -NoNewline
Write-Output "worker.env written ($($lines.Count) lines). Values not shown."
